version: '3.8'

services:
  react:
    container_name: react-app
    image: react-app
    networks:
      - app-network
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - /etc/nginx/templates:/etc/nginx/templates 
      - /etc/letsencrypt:/etc/letsencrypt 
    ports:
      - "80:80" 
      - "443:443" 
    networks:
      - app-network
    depends_on:
      - react
      - spring

networks:
  app-network:
    external: true

