version: '3.8'

services:
  react:
    container_name: react
    image: react-app
    networks:
      - app-network
    volumes:
      - /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

networks:
  app-network:
    external: true

